# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=200)),
                ('shipping_address', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('IN_PRODUCTION', 'In Production'), ('POST_PROCESSING', 'Post Processing'), ('QC', 'Quality Check'), ('PACKING', 'Packing'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('priority', models.CharField(choices=[('STANDARD', 'Standard'), ('RUSH', 'Rush'), ('EXPEDITED', 'Expedited')], default='STANDARD', max_length=20)),
                ('due_date', models.DateTimeField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(null=True)),
                ('raw_payload', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file_url', models.URLField()),
                ('model_file_name', models.CharField(max_length=255)),
                ('local_file_path', models.CharField(blank=True, max_length=500)),
                ('quantity', models.PositiveIntegerField()),
                ('layer_thickness_mm', models.CharField(max_length=20)),
                ('bounding_box_x', models.FloatField(null=True)),
                ('bounding_box_y', models.FloatField(null=True)),
                ('bounding_box_z', models.FloatField(null=True)),
                ('volume_ml', models.FloatField(null=True)),
                ('quantity_completed', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
