# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batching', '0001_initial'),
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        ('fleet', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=255)),
                ('formlabs_job_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('QUEUED', 'Queued'), ('PRINTING', 'Printing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('estimated_print_time_s', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='employees.employee')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='batching.printbatch')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.printer')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_jobs', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FailedPartRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('failure_type', models.CharField(choices=[('PRINT_FAILED', 'Print Failed'), ('QC_DEFECT', 'QC Defect'), ('POST_PROCESS_DAMAGE', 'Post-Processing Damage'), ('SHIPPING_DAMAGE', 'Shipping Damage')], max_length=30)),
                ('failure_reason', models.TextField(blank=True)),
                ('requeued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='orders.orderitem')),
                ('requeued_to_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batching.printbatch')),
                ('original_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.printjob')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('preform_scene_id', models.CharField(blank=True, max_length=100)),
                ('layer_thickness_mm', models.CharField(max_length=20)),
                ('layer_count', models.IntegerField(null=True)),
                ('volume_ml', models.FloatField(null=True)),
                ('form_file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.machinetype')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
            ],
        ),
        migrations.AddField(
            model_name='printjob',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='production.scene'),
        ),
        migrations.CreateModel(
            name='AsyncOperation',
            fields=[
                ('operation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('AUTO_ORIENT', 'Auto Orient'), ('AUTO_SUPPORT', 'Auto Support'), ('AUTO_LAYOUT', 'Auto Layout'), ('IMPORT_MODEL', 'Import Model'), ('PRINT', 'Print'), ('SAVE_FORM', 'Save Form File')], max_length=30)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('result', models.JSONField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('print_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.printjob')),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('position_z', models.FloatField(default=0)),
                ('orientation_x', models.FloatField(default=0)),
                ('orientation_y', models.FloatField(default=0)),
                ('orientation_z', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1.0)),
                ('has_supports', models.BooleanField(default=False)),
                ('in_bounds', models.BooleanField(default=True)),
                ('batch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batching.batchitem')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='production.scene')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PRINTING', 'Printing'), ('PRINTED', 'Printed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('batch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='batching.batchitem')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.printjob')),
                ('scene_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.scenemodel')),
            ],
        ),
    ]
