# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('build_volume_x', models.FloatField()),
                ('build_volume_y', models.FloatField()),
                ('build_volume_z', models.FloatField()),
                ('printer_family', models.CharField(choices=[('SLA', 'Stereolithography'), ('SLS', 'Selective Laser Sintering')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrintSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=20)),
                ('print_setting_name', models.CharField(default='DEFAULT', max_length=50)),
                ('layer_thickness_mm', models.CharField(max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
            options={
                'unique_together': {('machine_type', 'material', 'layer_thickness_mm')},
            },
        ),
    ]
