# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='QCChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qc.qcchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='QCInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('PARTIAL', 'Partial Pass'), ('FAILED', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('print_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspection', to='production.printjob')),
            ],
        ),
        migrations.CreateModel(
            name='QCItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_passed', models.PositiveIntegerField(default=0)),
                ('quantity_failed', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('photos', models.JSONField(default=list)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='qc.qcinspection')),
                ('print_job_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_results', to='production.printjobitem')),
            ],
        ),
    ]
