# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PACKING', 'Packing'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PACKING', max_length=20)),
                ('carrier', models.CharField(blank=True, choices=[('USPS', 'USPS'), ('UPS', 'UPS'), ('FEDEX', 'FedEx'), ('DHL', 'DHL')], max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('weight_oz', models.FloatField(null=True)),
                ('packed_at', models.DateTimeField(null=True)),
                ('shipped_at', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('packed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment')),
            ],
        ),
    ]
