# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('PRINTING', 'Printing'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error')], default='OFFLINE', max_length=20)),
                ('is_connected', models.BooleanField(default=False)),
                ('connection_type', models.CharField(blank=True, choices=[('USB', 'USB'), ('WIFI', 'WiFi'), ('ETHERNET', 'Ethernet')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.machinetype')),
                ('tank_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('volume_dispensed_ml', models.FloatField()),
                ('original_volume_ml', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartridges', to='fleet.printer')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREVENTITIVE', 'Preventative Maintenanve'), ('PREDICTIVE', 'Predictive Maintenance'), ('CORRECTIVE', 'Corrective Maintenance'), ('CONDITIONS', 'Conditions Maintenance')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.printer')),
            ],
        ),
    ]
