# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('layer_thickness_mm', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('COLLECTING', 'Collecting'), ('READY', 'Ready to Schedule'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('CLOSED', 'Closed')], default='COLLECTING', max_length=20)),
                ('priority', models.CharField(default='STANDARD', max_length=20)),
                ('must_schedule_by', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('is_reprint', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='orders.orderitem')),
            ],
        ),
    ]
