# Generated by Django 6.0 on 2025-12-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batching', '0001_initial'),
        ('core', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='original_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.failedpartrecord'),
        ),
        migrations.AddField(
            model_name='printbatch',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.machinetype'),
        ),
        migrations.AddField(
            model_name='printbatch',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='batching.printbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='batchitem',
            unique_together={('batch', 'order_item')},
        ),
    ]
